### ISSUE TITLE
Unable to run test cases in projects.

### ISSUE THREAD

**Issue by mikael-andersson91** [Mikael-RnD/UiPath-Test#1]
Should work with this command:
`test run "https://uipath-orchestrator.myorg.com" default -A myAccountForExternalApp -I myExternalAppId -S myExternalAppSecret --applicationScope "OR.Folders.Read OR.Settings.Read" -s "MyRobotTests"`

**Comment by mikael-andersson91** [comment]
-P, --project-path              The path to a test package file.
  -s, --testset                   The name of the test set to execute. The test set should use the latest version of the test cases. If the test set does not belong to the default folder (organization unit) it must be prefixed with the folder name, e.g. AccountingTeam\TestSet
  --out                           Type of result file
  -r, --result_path               Results file path
  -e, --environment               The environment to deploy the package to. Must be used together with the project path. Required when not using a modern folder.
  -w, --timeout                   The time in seconds for waiting to finish test set executions. (default 7200)
  -i, --input_path                The full path to a JSON input file. Only required if the entry-point workflow has input parameters and you want to pass them from command line.
  -u, --username                  Required. The Orchestrator username used for authentication. Must be used together with the password.
  -p, --password                  Required. The Orchestrator password used for authentication. Must be used together with the username.
  -t, --token                     Required. The Orchestrator OAuth2 refresh token used for authentication. Must be used together with the account name and client id.
  -a, --accountName               Required. The Orchestrator CloudRPA account name. Must be used together with the refresh token and client id.
  -A, --accountForApp             The Orchestrator CloudRPA account name. Must be used together with id, secret and scope(s) for external application.
  -I, --applicationId             Required. The external application id. Must be used together with account, secret and scope(s) for external application.
  -S, --applicationSecret         Required. The external application secret. Must be used together with account, id and scope(s) for external application.
  --applicationScope              Required. The space-separated list of application scopes. Must be used together with account, id and secret for external application.
  -o, --organizationUnit          The Orchestrator folder (organization unit).
  -l, --language                  The orchestrator language.
  -y, --disableTelemetry          Disable telemetry data.
  --traceLevel
  --help                          Display this help screen.
  --version                       Display version information.
  Orchestrator URL (pos. 0)       Required. The URL of the Orchestrator instance.
  Orchestrator Tenant (pos. 1)    Required. The tenant of the Orchestrator instance.

**Comment by mikael-andersson91** [comment]
Test executions are made, unable to retrieve results. Log from failed run:

`D:\a\ActionTest\ActionTest\TheProject\project.json
Detected schema version 4.0
uipcli.exe Error: 0 : NU1007: The runtime.json specified in the project 'D:\a\_temp\46ae[32](https://github.com/Mikael-RnD/ActionTest/runs/6435388024?check_suite_focus=true#step:4:32)05-cc73-44b6-95f3-3f64ef20e859\lib\net461\..\runtime.json' could not be found.
Compiling... done.
Building... done.
Signing... done.
Packaged project TheProject_Tests v1.0.106241158-alpha saved to C:\Users\runneradmin\AppData\Local\Temp\d758bbc640554024863fdb26ae5891b1.
Deploying package TheProject_Tests.1.0.106241158-alpha to tenant *** on https://cloud.uipath.com/...
FeedId for FolderId 2613568: .
Deploying project(s) C:\Users\runneradmin\AppData\Local\Temp\d758bbc640554024863fdb26ae5891b1\TheProject_Tests.1.0.106241158-alpha.nupkg to https://cloud.uipath.com/ and tenant *** to Package feed.
Status: OK
Key: C:\Users\runneradmin\AppData\Local\Temp\d758bbc640554024863fdb26ae5891b1\TheProject_Tests.1.0.106241158-alpha.nupkg
Body: {"Id":"TheProject_Tests","Version":"1.0.106241158-alpha"}
Process will be deployed in modern folder.
Deployed TheProject_Tests v1.0.106241158-alpha to folder Shared.
Running tests in set  on https://cloud.uipath.com/ (tenant ***) with a timeout of 7200 seconds...
Starting test set run for CI_2022-05-14T15:26:47.171[33](https://github.com/Mikael-RnD/ActionTest/runs/6435388024?check_suite_focus=true#step:4:33)60Z_TheProject_Tests_1.0.106241158-alpha...
Started test set CI_2022-05-14T15:26:47.1713[36](https://github.com/Mikael-RnD/ActionTest/runs/6435388024?check_suite_focus=true#step:4:36)0Z_TheProject_Tests_1.0.1062[41](https://github.com/Mikael-RnD/ActionTest/runs/6435388024?check_suite_focus=true#step:4:41)1[58](https://github.com/Mikael-RnD/ActionTest/runs/6435388024?check_suite_focus=true#step:4:58)-alpha with execution id 411[60](https://github.com/Mikael-RnD/ActionTest/runs/6435388024?check_suite_focus=true#step:4:60)5.
Running tests... 0 passed, 0 failed or canceled, 1 total. Waiting for 20s.
System.InvalidOperationException: Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Forbidden'
   at UiPath.Web.Client21_4.RobotLogs.<GetWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Orchestrator.Client.Util.ExceptionsHandler.<RunWithFriendlyExceptionMessages>d__1`1.MoveNext()
{"message":"You are not authorized!","errorCode":0,"result":null,"targetUrl":null,"success":false,"error":{"code":0,"message":"You are not authorized!","details":"You are not allowed to perform this operation.","validationErrors":null},"unAuthorizedRequest":true,"__abp":true}
   at UiPath.Orchestrator.Client.Util.ExceptionsHandler.<RunWithFriendlyExceptionMessages>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at UiPath.Orchestrator.Client.Endpoints.RobotLogs.<GetRobotLogs>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.CommandLine.Services.Impl.TestService.<GetRobotLogs>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at UiPath.CommandLine.Services.Impl.TestService.<>c__DisplayClass22_0.<<SaveExecution>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at UiPath.CommandLine.Services.Impl.TestService.<SaveExecution>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at UiPath.CommandLine.Services.Impl.TestService.<>c__DisplayClass20_0.<<ExecuteTestSet>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at UiPath.CommandLine.Services.Impl.TestService.<ExecuteTestSet>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at UiPath.CommandLine.Services.Impl.TestService.<Run>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.CommandLine.Services.Impl.OptionsParser.<>c__DisplayClass7_0.<<WithTraceLogging>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at UiPath.CommandLine.Services.Impl.OptionsParser.<RunOptions>d__6.MoveNext()`

**Comment by mikael-andersson91** [comment]
Application scope:
OR.Assets OR.BackgroundTasks OR.Execution OR.Folders OR.Jobs OR.Machines.Read OR.Robots.Read OR.Settings.Read OR.Tasks OR.TestDataQueues OR.TestSetExecutions OR.TestSets OR.TestSetSchedules OR.Users.Read
